name: product_navigator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_ui_auth: ^1.15.0
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  widget_and_text_animator: ^1.1.5
  animated_text_kit: ^4.2.2
  flutter_native_splash: 2.4.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.25.2

flutter:
  uses-material-design: true

  fonts:
  - family: Pacifico
    fonts:
      - asset: assets/fonts/Pacifico-Regular.ttf
  assets:
    - assets/images/beautyproductsnew.webp
    - assets/images/beautyproducts.jpg
    - assets/images/foodproducts.jpg
    - assets/images/itproducts.jpg
    - assets/images/laptop.jpg
    - assets/images/moblies.jpg
